const dateActionTypes = {
    SET_CURRENT_DATE: 'SET_CURRENT_DATE',
    SET_CURRENT_YEAR: 'SET_CURRENT_YEAR',
    SET_CURRENT_MONTH_NUM: 'SET_CURRENT_MONTH_NUM',
    SET_CURRENT_MONTH_STR: 'SET_CURRENT_MONTH_STR',
    SET_MONTH_DAYS: 'SET_MONTH_DAYS'
}

export default dateActionTypes